name: checks

on: [push, pull_request]

jobs:
  rust-fmt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt

    - name: Check formatting (logitech-hidpp)
      run: cargo fmt --manifest-path logitech-hidpp/Cargo.toml -- --check

    - name: Check formatting (solaars-cli)
      run: cargo fmt --manifest-path solaars-cli/Cargo.toml -- --check

    - name: Check formatting (solaarsd)
      run: cargo fmt --manifest-path solaarsd/Cargo.toml -- --check

  rust-clippy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y libudev-dev libusb-1.0-0-dev

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy

    - name: Clippy (logitech-hidpp)
      run: cargo clippy --manifest-path logitech-hidpp/Cargo.toml -- -D warnings

    - name: Clippy (solaars-cli)
      run: cargo clippy --manifest-path solaars-cli/Cargo.toml -- -D warnings

    - name: Clippy (solaarsd)
      run: cargo clippy --manifest-path solaarsd/Cargo.toml -- -D warnings
